### ISSUE TITLE
Gambarnya belum kelihatan

### ISSUE THREAD

**Issue by Bhaskaraa** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-lentera-studios#1]
Ada gambar gambar yang belum kelihatan atau mungkin belum ke upload ges, logo diatas sama lomba lombanya, mungkin bisa di upload gambar gambarnya gais, SEMANGADD!!

**Comment by fikrihaykal** [comment]
Sudah ditambahkan ya
