### ISSUE TITLE
bisa register dengan semua kolom kosong, tanpa ada error massage

### ISSUE THREAD

**Issue by nashirat** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-lentera-studios#11]
![image](https://user-images.githubusercontent.com/55182333/67179073-4b79e300-f3ff-11e9-9be4-1d5f7e7d016b.png)

**Comment by fikrihaykal** [comment]
Sudah diperbaiki validasi formnya, terima kasih koreksinya
