### ISSUE TITLE
Perbaiki ikon panah dari bawah ke atas

### ISSUE THREAD

**Issue by MilenFifi** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-lentera-studios#12]
panah ini buat lebih responsif dong, masak panahnya diem aja nggak ilang atau kalau turun dikit bisa keliatan ga perlu scroll sampe bawah banget dulu baru bisa ada ikon ke atas. waktu ke atas dikit aja jg ga ilang jadi agak gak enak gitu liatnya
![Uploading Screenshot_2019-10-21-14-35-21-010_com.android.chrome.png…]()

**Comment by MilenFifi** [comment]
maap sepertinya ss ku ga sepenuhnya ke upload :v

**Comment by fikrihaykal** [comment]
Position udah dirubah menjadi fixed. Terima kasih sarannya
