### ISSUE TITLE
cart harus login dulu gan

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-lentera-studios#15]
![image](https://user-images.githubusercontent.com/49645946/67191554-02845780-f41c-11e9-80fb-447b21058f07.png)
hehehehhehe

**Comment by fikrihaykal** [comment]
Sudah diupdate dan ditambahkan pengecekan sesi
Terima kasih koreksinya
