### ISSUE TITLE
checkout.php

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-lentera-studios#17]
![image](https://user-images.githubusercontent.com/49645946/67191737-5c851d00-f41c-11e9-8974-65e612d4f1f4.png)
harusnya header ke tugas2-web-lentera-studios/paid.php

**Comment by fikrihaykal** [comment]
Sudah diupdate URLnya
Terima kasih koreksinya
