### ISSUE TITLE
password recovery issue

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-lentera-studios#18]
![image](https://user-images.githubusercontent.com/49645946/67191928-c1407780-f41c-11e9-84a6-1cf49b5fadbc.png)

**Comment by fikrihaykal** [comment]
Untuk fitur ini belum bisa diimplementasikan, jadi dengan berat hati kami menghapus fitur password recovery terlebih dahulu
