### ISSUE TITLE
account issue

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-lentera-studios#19]
![image](https://user-images.githubusercontent.com/49645946/67192014-edf48f00-f41c-11e9-9ec7-e6feb9047822.png)
jika ku klik account maka masuknya ke:
![image](https://user-images.githubusercontent.com/49645946/67192036-fd73d800-f41c-11e9-962d-c712cc324c3d.png)

**Comment by fikrihaykal** [comment]
Sudah diupdate URLnya
