### ISSUE TITLE
Menunya belum ke link

### ISSUE THREAD

**Issue by Bhaskaraa** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-lentera-studios#2]
beberapa menunya belum berfungsi, mungkin belum ke link ke pagenya, jadi mungkin bisa dihubungkan ke page ya gaiz, SEMANGADD!

**Comment by widyantarif** [comment]
untuk saat ini kami hanya menyediakan menu competition. untuk menu yang lain masih belum diperlukan.
