### ISSUE TITLE
Tidak Bisa Logout

### ISSUE THREAD

**Issue by DSlite** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-lentera-studios#6]
Tidak bisa melakukan logout, munculnya object not found, mungkin kesalahan pada href atau link .
![image](https://user-images.githubusercontent.com/17781660/66985703-8de1ae00-f0e7-11e9-99b9-7cd13696080b.png)

**Comment by widyantarif** [comment]
link sudah dibenahi
